### ISSUE TITLE
Please make error message more descriptive

### ISSUE THREAD

**Issue by evansrl** [textileio/textile#102]
Hi! If you make a project with the same name as a preexisting project (not necessarily your own), it fails with the only Error Message being "Error! Scope does not own project." Could you change it to "Error! Project must not have same name as preexisting project. Try a different name"?

Output is as follows:

[wotder@localhost ~]$ textile whoami
> You are evansrl@protonmail.com
[wotder@localhost ~]$ textile teams
NAME            ID                                    
something       d0e5b7d7-9aa7-493d-8c7d-c5ff15740516

> Found 1 teams
[wotder@localhost ~]$ textile switch
> Switching to something
> Success! Switched to something
[wotder@localhost ~]$ textile projects ls
NAME    ID                                      STORE                                 
test2   622974e5-c3ce-4c1c-871d-631e7e79bda8    7a623e49-e9f5-4e44-b2ab-42010a69afdd

> Found 1 projects for current scope
[wotder@localhost ~]$ textile project init test
> Error! Scope does not own project
[wotder@localhost ~]$ textile project init test1
> Success! Initialized empty project in /home/wotder/.textile
[wotder@localhost ~]$ touch test1/hello.txt

**Comment by sanderpick** [comment]
Hey @evansrl, thanks for the report. We're most likely going to make project and team names non-unique. However, I will add a similar message to bucket creation, since those will remain globally unique.
