### ISSUE TITLE
Bucket rm doesn't remove file from cloud.textile.io

### ISSUE THREAD

**Issue by asutula** [textileio/textile#103]
Getting reports from users this is the case. The CLI shows the file has been successfully removed, but it still is visible on cloud.textile.io/dahsboard.

**Comment by sanderpick** [comment]
👀

**Comment by sanderpick** [comment]
This must be related to nginx caching or something. I wasn't able to reproduce locally. I'll dig in there.

**Comment by sanderpick** [comment]
This should be fixed. I disabled the proxy caching for now.
