### ISSUE TITLE
Auto generate and update a bucket IPNS address

### ISSUE THREAD

**Issue by andrewxhill** [textileio/textile#118]
Low hanging fruit for bucket interop. 

- create a new address on Bucket init and auto update it on any push. 
- create a CLI method for getting a bucket IPNS address

**Comment by janaka** [comment]
Is this about doing the equivalent of `ipfs name publish` to get a PEER_ID for a DNSlink record?

**Comment by carsonfarmer** [comment]
Yup, exactly.
