### ISSUE TITLE
Catch ErrServerClosed style server shutdown error

### ISSUE THREAD

**Issue by andrewxhill** [textileio/textile#119]
https://github.com/textileio/textile/blob/fb82b7b084e55b3939a8fdd1c3d7952a457433b5/api/server.go#L146

There is an edge case for an error that we don't need/want to log, where the proxy startup errs due to manual forced shutdown(ctrl+c). This was fiixed over in powergate https://github.com/textileio/powergate/pull/153/files#diff-44a527ea72ea9572e1cf71c7f1e2a0f0R267

holding on a fix until after ongoing refactor lands

**Comment by sanderpick** [comment]
Nice, I'm doing that on https://github.com/textileio/textile/tree/sander/refactor
