### ISSUE TITLE
how to know bucket-related urls?

### ISSUE THREAD

**Issue by asutula** [textileio/textile#157]
this may just be an issue of getting and answer from someone who knows and documenting it, or maybe we need a new cli command or to augment an existing one...

how can I discover/see whatever slug/token/id/string/whatever for a bucket that I would use to construct a url for viewing the bucket on the hub gateway, hub website endpoint, ipfs gateway, etc?

maybe there should just be a way to easily list all these urls

**Comment by asutula** [comment]
using the cli as is, I feel like I don't know how to find this information

**Comment by sanderpick** [comment]
Yep, agreed... I have a todo to spit out the URL during init

**Comment by andrewxhill** [comment]
something like a `links` command that spit out ipns cid, gateway link, and subdomain link would be mega

**Comment by andrewxhill** [comment]
i could pr that if you think it's useful

**Comment by sanderpick** [comment]
To cover all bucket info, I'm thinking we can just print a bunch of info with a single command, `tt buckets`. For each bucket, that would show,
- Thread link, website link, IPNS website link
- A `bucket init` command with the needed flags for pulling (like `git clone`-ish)
