### ISSUE TITLE
Bug after deleting org "> Error! User is not an org member"

### ISSUE THREAD

**Issue by samuelandert** [textileio/textile#193]
After trying to delete an org with the CLI, my user account will always through me the Error: User is not an org member, on almost any tt command. Do you have an idea, what went wrong?
```
samuelandert@Samuels-MBP omo % tt orgs ls
> Error! User is not an org member
samuelandert@Samuels-MBP omo % tt whoami 
> Error! User is not an org member
samuelandert@Samuels-MBP omo % tt threads ls
> Error! User is not an org member
samuelandert@Samuels-MBP omo % tt orgs rm omoearth   
> Error! User is not an org member
samuelandert@Samuels-MBP omo % tt org create
Choose an Org name: oomearth
> Error! User is not an org member
samuelandert@Samuels-MBP omo % tt org create
Choose an Org name: test
> Error! User is not an org member
```

**Comment by sanderpick** [comment]
Hey @samuelandert - Are you by any chance in a bucket directory that was created with the org?

**Comment by samuelandert** [comment]
Yes, and I solved the problem by deleting the .textile/config.yml ;)

**Comment by sanderpick** [comment]
Cool, thanks for the report! I created https://github.com/textileio/textile/issues/195 to help improve this situation.
