### ISSUE TITLE
">Error ! Thread not found" when trying to push an orga bucket

### ISSUE THREAD

**Issue by samuelandert** [textileio/textile#194]
```
samuelandert@Samuels-MBP omo % tt bucket push src/ .
Add 55 files? Press ENTER to confirm: █
Add 55 files? Press ENTER to confirm: █
> Pushing src/App.svelte to App.svelte

0 B / 4.79 kB [__________________________________________________] 0.00% ? p/s ?> Error! Thread not found

```

**Comment by sanderpick** [comment]
This could also be similar to #193. Could the bucket config `.textile/config.yml` be from an old org?

**Comment by samuelandert** [comment]
Its the same folder, where I deleted it, but I created a new orga bucket and thus a fresh config.yaml 
I had this bug already before, which was the reason I tried to delete the org ;)

**Comment by samuelandert** [comment]
When I init the bucket in the scope of the user account instead to the organization, the push works without any problem.

**Comment by sanderpick** [comment]
What happens if you choose "Create new" when you're asked to choose a threadDB for the new bucket? 

I doubt this is related, but the _just now_ released CLI might help just so we're on the same page: https://github.com/textileio/textile/releases/tag/v1.0.2

**Comment by samuelandert** [comment]
Thanks, just updated to v1.0.2 

Do you mean create a new bucket with "tt bucket init" or something else?
I never get to the question of being able to choose a threadDB.

**Comment by sanderpick** [comment]
When you initialize a new bucket like,
```
tt bucket init --org=<your-org-username>
```
First, you can enter an optional name,
```
 Enter a name for your new bucket (optional): Foo
```
Then you should see a scrollable list of your existing thread DBs, and an option to create a new one:
```
Use the arrow keys to navigate: ↓ ↑ → ←
? Buckets are written to a threadDB. Select or create a new one:
  bafktwufvprshu3illr6b6265nirher6xe4h4ewq3gpavouwozzyifcq default
  bafk7a6g2nd25awa372axygu3skcs6axj7dscuduum67d4lvemtcrhbq Sander
  ▸ Create new
(Type: db)
```

Try _Create new_ at the bottom of the list. That will generate a new database under your org.

**Comment by samuelandert** [comment]
Yes this time, it came up. Maybe it was the update to 1.0.2! Muchas gracias!

**Comment by sanderpick** [comment]
Great! Thanks for the report.
