### ISSUE TITLE
Impossible to register with a slow email setup

### ISSUE THREAD

**Issue by Stebalien** [textileio/textile#196]
It can easily take several minutes for me to receive an email. This makes it impossible to confirm my email to register an account.

Ideally, the initialization process would:

1. Be resumable.
2. Re-poll the textile hub when it times out.

**Comment by sanderpick** [comment]
Hey @Stebalien! Thanks for jumping in. 

We could just make the timeout very high, like an hour.

**Comment by Stebalien** [comment]
That works. I'd still consider making the process resumable (i.e., if I run `tt init` after starting the process before, it could ask if I want to resume registration). But an increased timeout is enough for most cases.

**Comment by Stebalien** [comment]
Thanks!

**Comment by sanderpick** [comment]
Ah yeah, good call. Here's an issue for that: https://github.com/textileio/textile/issues/206
