### ISSUE TITLE
PKI Inboxing Service

### ISSUE THREAD

**Issue by sanderpick** [textileio/textile#233]
Allow verified PKIs to leave messages for other PKIs. This would still require API access via an API key, perhaps throttled / limited to some limits later on.

**Comment by jsonsivar** [comment]
Just adding some more info here based on the call we had with @andrewxhill and @carsonfarmer earlier.  We currently do the challenge method to authenticate users against the hub, so assuming this inboxing service will work for such identities. 

Took an initial cut at the possible interface for it but of course subject to change based on this discussion:
```
func (c *Client) SendMessage(ctx context.Context, payload []byte, signature string, recipientPubKey string) error
func (c *Client) ListenForMessages(ctx context.Context) (<-chan MessageEvent, error)
```

Some notes to go along with that:
- assuming this would be on the `hub` client?
- the token will be in the context as usual
- does the client need to encrypt the message before sending it across the wire?

**Comment by sanderpick** [comment]
Nice @jsonsivar, this looks good.

> so assuming this inboxing service will work for such identities

Yep.

> - assuming this would be on the hub client?
> - the token will be in the context as usual
> - does the client need to encrypt the message before sending it across the wire?

Yes to all of those.

We did something similar on the old textile node and ended up needed some more things like:

- Mark a message as read.
- Delete a message.
- Paginate all/new messages. Just listening doesn't work in the case where you've been offline.
