### ISSUE TITLE
Add version command to hub and buck

### ISSUE THREAD

**Issue by asutula** [textileio/textile#240]
Something that will print out the release version or, in the case of a non-release build, the git hash

**Comment by asutula** [comment]
This looks like a cool way of doing it without having to manually maintain a version number file

https://blog.kowalczyk.info/article/vEja/embedding-build-number-in-go-executable.html

**Comment by jsign** [comment]
Agreed. We should also include the version in the output logs, so it would help us understand what code was running while debugging something.

**Comment by andrewxhill** [comment]
piling on :) 

would be great to have a `hub update` via something like https://github.com/rhysd/go-github-selfupdate
