### ISSUE TITLE
PullPath on a folder in Windows gives "invalid path" error

### ISSUE THREAD

**Issue by jsonsivar** [textileio/textile#268]
When calling `PullPath` while running `buckd` on a Windows machine, it gives the following error:
![image](https://user-images.githubusercontent.com/18757934/87435893-4e82b800-c5ba-11ea-95b4-3b724439a075.png)

Since this isn't happening on Mac or Linux assuming the `path` library functions are introducing some OS-specific characters (plus some weird escaping). 

More information about the environment:
OS: Windows 10 64-bit
Textile: v1.0.13-0.20200707162859-d8131f5afba4
Go: 1.14

**Comment by studna** [comment]
https://github.com/textileio/textile/blob/e40231f758b6652b5b9ae48085842f46fb0229f6/api/buckets/service.go#L874

I think the problem might be with `filepath.Join`, which is used for joining paths in file above ☝️ . Maybe some of these `filepath.Join` can be replaced with `path.Join` to keep slashes platform-agnostic?

**Comment by sanderpick** [comment]
Sounds likely! Taking a look now...

**Comment by sanderpick** [comment]
Sadly I don't have a good way to quickly test this on Windows. Can one of you check after I do a release in a few min?

**Comment by jsonsivar** [comment]
Hey I was able to setup a win env and test this to confirm it works now!
