### ISSUE TITLE
Accessing bucket content returns data with 404 response

### ISSUE THREAD

**Issue by ericglau** [textileio/textile#272]
When I access any content on my bucket (which was uploaded from Textile hub command line) through a browser, I am able to see the contents but the HTTP response code is 404.  This seems to be causing an issue with the tools that I am using since the HTTP response code is not OK. 

For example, if you go to this URL in Brave, you see the XML content but Brave shows a 404 error at the top: https://bafkt5edpkmbejifojfarn2wawtc62t36gy4te7bftd64cgjsy7gv2ui.thread.hub.textile.io/buckets/bafzbeidxwtnl7mwj62s35b75cezp2lzsbbecwcv3gt4kmz5qsc2zlqjhsu/com/github/ericglau/project-a/1.0.0-SNAPSHOT/maven-metadata.xml

If you paste that URL in https://websniffer.cc/ , it also shows that the HTTP response header is 404.

**Comment by sanderpick** [comment]
Thanks for the report! Fix landed in here: https://github.com/textileio/textile/pull/273

I'll deploy to hub.textile.io once the docker images are published (~30min).

**Comment by sanderpick** [comment]
Looks like 200s on your file now. Thanks again for the report.
