### ISSUE TITLE
listPath API appears to be dropping details in itemList

### ISSUE THREAD

**Issue by andrewxhill** [textileio/textile#279]
Just tried this against localhost and hub.next. I've created a bucket with some nested files, here's an example

http://bafkwi2lglzxszuar5sxi4egv57mztrui2vc7wkr4b4fqpwbixx242ky.thread.hub.next.textile.io/buckets/bafzbeieqt67mdbunw7fo2rgcsko2rldg2bhursrkhxfwt67pu64ehzfb2q

you can verify that all the leafs do contain real data http://bafkwi2lglzxszuar5sxi4egv57mztrui2vc7wkr4b4fqpwbixx242ky.thread.hub.next.textile.io/buckets/bafzbeieqt67mdbunw7fo2rgcsko2rldg2bhursrkhxfwt67pu64ehzfb2q/images/1595107073/thumb/screen_shot_2020_07_09_at_1.02.17_pm.png

when calling `listPath` against that first directory, `images` it gives only the first level of metadata and then seems to drop all the leaf data. here's the response. you can see it has the right number of items in the itemList, just no metadata.

```
{
  "cid": "QmXfdKt2KCvHPhdhCYWEhHxkZQyqqLmu8JScmK3uBirs7W",
  "name": "1595107073",
  "path": "/ipfs/bafybeigmsfquq5ztvezig36yjvyqv2pyojbbfuclghzlfqzuvc2emr57fy/images/1595107073",
  "size": 60680,
  "isdir": true,
  "itemsList": [
    {
      "cid": "",
      "name": "",
      "path": "",
      "size": 0,
      "isdir": false,
      "itemsList": []
    },
    {
      "cid": "",
      "name": "",
      "path": "",
      "size": 0,
      "isdir": false,
      "itemsList": []
    }
  ]
}
```

**Comment by andrewxhill** [comment]
if i call listPath on the nested dir, `images/1595107073` it gives back similar. where the first layer deep is correct and then the rest is just not filled out

```
{
  "item": {
    "cid": "QmXfdKt2KCvHPhdhCYWEhHxkZQyqqLmu8JScmK3uBirs7W",
    "name": "1595107073",
    "path": "/ipfs/bafybeigmsfquq5ztvezig36yjvyqv2pyojbbfuclghzlfqzuvc2emr57fy/images/1595107073",
    "size": 60680,
    "isdir": true,
    "itemsList": [
      {
        "cid": "bafkreigjrt36yjbqyk64ooo3rhvpusxxtgsh5w2htqmsdgdneueevm36se",
        "name": "screen_shot_2020_07_09_at_1.02.17_pm.png",
        "path": "/ipfs/bafybeigmsfquq5ztvezig36yjvyqv2pyojbbfuclghzlfqzuvc2emr57fy/images/1595107073/screen_shot_2020_07_09_at_1.02.17_pm.png",
        "size": 54291,
        "isdir": false,
        "itemsList": []
      },
      {
        "cid": "QmZu1CNNyJeQG5yEj1URbywJvPUDz7sUv6zEHJfcccNyEv",
        "name": "thumb",
        "path": "/ipfs/bafybeigmsfquq5ztvezig36yjvyqv2pyojbbfuclghzlfqzuvc2emr57fy/images/1595107073/thumb",
        "size": 6251,
        "isdir": true,
        "itemsList": [
          {
            "cid": "",
            "name": "",
            "path": "",
            "size": 0,
            "isdir": false,
            "itemsList": []
          }
        ]
      }
    ]
  },
  "root": {
    "key": "bafzbeieqt67mdbunw7fo2rgcsko2rldg2bhursrkhxfwt67pu64ehzfb2q",
    "name": "io.textile.imbuck",
    "path": "/ipfs/bafybeigmsfquq5ztvezig36yjvyqv2pyojbbfuclghzlfqzuvc2emr57fy",
    "createdat": 1595107027723918800,
    "updatedat": 1595107074854089500,
    "thread": "bafkwi2lglzxszuar5sxi4egv57mztrui2vc7wkr4b4fqpwbixx242ky"
  }
}
```

**Comment by andrewxhill** [comment]
in that second example... it actually feels right to me. since for any kind of performance, i may not want to pull the full tree into the app right away. so i think the fix is probably to drop the `itemsList` from the object in the nested dir. maybe this is what actually being returned from the api, but some grpc types make it stub out that empty object...

**Comment by sanderpick** [comment]
That’s by design actually... the CLI used the slice count to determine how many things are in a directory. We just return the first level since you can just do another request on the inner level, rather than deciding for the user to return all data / metadata
