### ISSUE TITLE
Add a listPathsFlat option to the buckets API

### ISSUE THREAD

**Issue by andrewxhill** [textileio/textile#297]
yesterday I PRd this method to @textile/buckets but perhaps it lives in the core api. https://github.com/textileio/js-hub/pull/376/files#diff-0f61dbdec1fdac42bc99c30ab20c6c41R277

in short, it allows me to request a list of all paths in the directory as a flat string list,

```
     [
       'mybuck',
       'mybuck/.textileseed',
       'mybuck/dir1',
       'mybuck/dir1/file1.jpg',
       'mybuck/path',
       'mybuck/path/to',
       'mybuck/path/to/file2.jpg'
     ]
```

(it also includes an option to omit directories in the list)

This is a really useful method when doing pushes to existing buckets over the API. in the Buckets lib for Github Actions, I use this list object to 

1. When pushing a new version of the bucket, I can quickly mark which files are being replaced (remove them from the list)
2. Then I can delete all the remaining leafs to clean up my bucket. 

This flow is helpful, since I'm sending file by file to the remote API. Additionally, it feels nicer not to wipe the entire bucket first in case any error occurs. 

**Alternatively//additionally**

Not sure if Buckets could handle something like a WriteTransaction endpoint. Then I could potentially implement a flow that wipes the entire bucket, sends all the changes, and close the transaction. Ideally roll-back safe if there is any error. Not sure though.

**Comment by sanderpick** [comment]
`buck` handles this by walking the paths and listing each one. Letting the server list an entire bucket recursively is quite dangerous. This is also why doing a full bucket size calc on a private bucket is not safe.

**Comment by andrewxhill** [comment]
okay nice. so that pr in the client is on track, 💰 .
