### ISSUE TITLE
Add per bucket archive storage config option

### ISSUE THREAD

**Issue by asutula** [textileio/textile#339]
Add ability to provide a custom storage config for a single call to `Buckets.Archive`

**Comment by jimmylee** [comment]
Also would love this, would this custom storage config also support miner selection?

**Comment by asutula** [comment]
Yes, I think it would.

**Comment by jimmylee** [comment]
# no 1

This is the most obvious place the custom config will be used. This is for one-off storage deals.

<img width="1560" alt="Screen Shot 2020-09-23 at 9 49 24 AM" src="https://user-images.githubusercontent.com/310223/94043685-1817a500-fd82-11ea-939f-bbcedd661434.png">

# no 2

I haven't added the custom config options here yet but they will be used for your main bucket archies.

<img width="1153" alt="Screen Shot 2020-09-23 at 9 51 19 AM" src="https://user-images.githubusercontent.com/310223/94043964-66c53f00-fd82-11ea-93ff-9d883ccc71dc.png">
