### ISSUE TITLE
ListPath and ListIPFSPath return response closed without headers

### ISSUE THREAD

**Issue by andrewxhill** [textileio/textile#355]
`Response closed without grpc-status (Headers only)`

on some buckets, particularly very large buckets, the response to listpath will never succeed. 

added private details in slack

**Comment by jimmylee** [comment]
These are the files where it could happen on our end.

https://github.com/filecoin-project/slate/blob/main/node_common/upload-fs.js
https://github.com/filecoin-project/slate/blob/main/node_common/upload.js
https://github.com/filecoin-project/slate/blob/main/node_common/managers/viewer.js
https://github.com/filecoin-project/slate/blob/main/pages/api/data/bucket-remove.js
https://github.com/filecoin-project/slate/blob/main/pages/api/data/get.js
https://github.com/filecoin-project/slate/blob/main/pages/api/data/remove-multiple.js
https://github.com/filecoin-project/slate/blob/main/pages/api/data/remove.js
