### ISSUE TITLE
Add a flag to not encrypt a new bucket when initializing

### ISSUE THREAD

**Issue by andrew** [textileio/textile#358]
Similar to #350 and #351, I'm trying to script the use the cli and the interactive options make it tricky.

One option when creating a new bucket that doesn't appear to be configurable via a flag is to not encrypt the bucket, ideally something like:

    hub buck init --private=false -n my-newly-scripted-bucket

**Comment by sanderpick** [comment]
Hey @andrew, that is possible currently, perhaps the short `-n` with a space is causing an issue. I just tried the following and worked fine w/o any interactive interruption:

```
hub buck init --private=false --name=mybuck --thread=bafk3r3z4jxkjfesrgr2m2e2qxnm7jl6tjo7nq2ruzo32z4cqmlmvj5y
```

**Comment by andrew** [comment]
Ah yeah, that works with --name=, thanks!
