### ISSUE TITLE
Textile buckets sometimes go below zero on remove requests

### ISSUE THREAD

**Issue by andrewxhill** [textileio/textile#376]
As reported in Slate.

It seems to come from a strange case where an upload fails or gets stuck or other (still unresolved what this is)
But then on a request to remove a path seems to put the quota below zero.

Quick fix is here: https://github.com/textileio/textile/pull/375 but need to better understand and get a long term fix for that.

**Comment by andrewxhill** [comment]
The situation where this is appearing seems to be when you remove a user's only bucket, leaving them with no bucket at all (at which point it triggers <0 in some cases)

**Comment by jimmylee** [comment]
Thanks for tracking this!
