### ISSUE TITLE
Textile Space not Updating after a "hub buck push"

### ISSUE THREAD

**Issue by MamaOmo** [textileio/textile#378]
After using "hub buck push" the files are not n the textile gateway (XXX.textile.space....)

Reproduce:
I have created a  new Bucket
The pushed Content to it
then updated app.js file
pushed changes
![3](https://user-images.githubusercontent.com/67921883/95908968-0e3ffb00-0d9e-11eb-9ff9-351157c5af6a.png)
![2](https://user-images.githubusercontent.com/67921883/95908973-0f712800-0d9e-11eb-9d59-7e07607016ef.png)
![1](https://user-images.githubusercontent.com/67921883/95908978-10a25500-0d9e-11eb-8273-8f51167a9313.png)

After that the file on textile space is not updated
https://bafzbeieiwlpc3xlzb72atobgrv6bcssxb6j6dps2g7f7zmncmlogucsnm4.textile.space/app.js
But on the link on Index site point to the right file

Index Page
https://hub.textile.io/thread/bafkxumvuqmky6nustqkohwhaj2vsighd5hx4t2aa4hxiupoigoehnwi/buckets/bafzbeieiwlpc3xlzb72atobgrv6bcssxb6j6dps2g7f7zmncmlogucsnm4

Link to app.js
https://hub.textile.io/thread/bafkxumvuqmky6nustqkohwhaj2vsighd5hx4t2aa4hxiupoigoehnwi/buckets/bafzbeieiwlpc3xlzb72atobgrv6bcssxb6j6dps2g7f7zmncmlogucsnm4/app.js

+ app.js: bafkreignrkhots7fczqxmeead7c5fp5h3df6ne2uz3zsubnqwtn4atqd6i
> Your bucket links:
> https://hub.textile.io/thread/bafkxumvuqmky6nustqkohwhaj2vsighd5hx4t2aa4hxiupoigoehnwi/buckets/bafzbeieiwlpc3xlzb72atobgrv6bcssxb6j6dps2g7f7zmncmlogucsnm4 Thread link
> https://hub.textile.io/ipns/bafzbeieiwlpc3xlzb72atobgrv6bcssxb6j6dps2g7f7zmncmlogucsnm4 IPNS link (propagation can be slow)
> https://bafzbeieiwlpc3xlzb72atobgrv6bcssxb6j6dps2g7f7zmncmlogucsnm4.textile.space Bucket website

**Comment by MamaOmo** [comment]
Also tried with second account on second macbook with same result

**Comment by andrewxhill** [comment]
looks like a combination of

- waiting for IPNS update times
- browser caching

led to this. 

note: it may be worth tweaking the browser cache ttl if there is one on the space gateway
