### ISSUE TITLE
client.updateCollection returns "collection not found" error

### ISSUE THREAD

**Issue by Schwartz10** [textileio/textile#387]
I'm following the example https://textileio.github.io/js-textile/docs/hub.client.updatecollection, (not _quite_ identical, but extremely close).

Also, related question - does the update command update the name of the collection based on schema? Is it possible to update the schema of a collection without changing the name?

I'm guessing it's impossible, based on the way to function call looks, to update both a collection's schema and its name in 1 updateCollection call?

**Comment by carsonfarmer** [comment]
For the second question, it is actually _not_ possible to update the name of a collection currently. You use the name to reference the existing collection. So you can only update indexes, write/read functions, and its schema.

**Comment by carsonfarmer** [comment]
Also, you are updating a collection that does indeed already exist under that name? Can you confirm the collection is already in the db?

**Comment by Schwartz10** [comment]
Ah this makes sense. I was attempting to change the name (since I think the example i pasted above shows changing a name). 

It makes a lot more sense (and is way more useful) to change the schema and other attributes rather than the name itself.
