### ISSUE TITLE
CID or name does not exist in bucket anymore, but still has gateway URL?

### ISSUE THREAD

**Issue by jimmylee** [textileio/textile#425]
Hey everyone! Strange issue here.

When we delete files from a bucket on Slate, we are able to provide two things:

```
{
  data: {
    cids: [ 'bafybeidnld72eb2rulrskiswetpg2qrazw5uhmemqoms24l3x7tychx5uq' ],
    ids: [ 'data-0444ef3e-c9f4-4ab5-9ff6-db658028ec95' ]
  }
}
```

* The CID at the time we pushPath
* The ID we generate on our end for the `name` of the file we `buckets.pushPath`

And this works out pretty nicely! We are able to match at least the `name` or `cid`

```
{
  cid: 'bafybeid5mqzuxqmhtj45g7exsb4sfdofiduiuo5agtg6fyi6fbiyraqz24',
  name: 'data-ba42a437-44aa-41fe-8a4e-1ab78581e144',
  path: '/ipfs/bafybeia6zvagxjmvcfsrcrjfxp4ml6peraijt3qji3uiqcxgd7svox52gq/data-ba42a437-44aa-41fe-8a4e-1ab78581e144',
  size: 5464826,
  isDir: false,
  items: [],
  count: 0,
  metadata: undefined
}
```

However there is a problem, there exists a gateway URL 

```
https://slate.textile.io/ipfs/bafybeidnld72eb2rulrskiswetpg2qrazw5uhmemqoms24l3x7tychx5uq
```

That does not exist in the bucket at all. At first I thought the CID had changed, but I can't match the name `data-0444ef3e-c9f4-4ab5-9ff6-db658028ec95` either.

I'm not sure exactly what to do here, if its not in the bucket maybe we can just remove our reference to it? But then I wonder which bucket this file lives in? Should we not worry about it and just kill our reference?

**Comment by sanderpick** [comment]
Hey @jimmylee, I'm not sure I follow... you're saying that the file behind the above URL (dolphin video) is not in the bucket? Could you share the bucket link (the one with `/thread/` in the URL)?

**Comment by jimmylee** [comment]
Hey sorry about the late response, @carsonfarmer helped me confirm we had data that wasn't on the bucket anymore, so we're just letting removal fail silently.
