### ISSUE TITLE
Locked out of the hub + hub "Response closed without headers"

### ISSUE THREAD

**Issue by Schwartz10** [textileio/textile#426]
I'm experiencing an issue similar to this person in the Textile slack [thread](https://textile-public.slack.com/archives/CCRJZJT26/p1606296058244300)

`clientWithKeyInfo.getTokenChallenge` throws `Response closed without headers`

```js
      const clientWithKeyInfo = await Client.withKeyInfo({
        key: HUB_KEY,
        secret: HUB_SECRET,
      });
      const identity = await PrivateKey.fromRawEd25519Seed(
        this.authenticationCreds.secret
      );
      // everything looks ok up until here
      this.authorizationCreds.token = await clientWithKeyInfo.getTokenChallenge(
        identity.public.toString(),
        (challenge: Uint8Array) => identity.sign(challenge)
      );
      // Response closed without headers
```

After experiencing this error, I upgraded my @textile/hub package to version ^1.2.1. The error continued.

After that I:

- Updated my Hub binary to v2.1.7
- Ran Hub login, typed in my email (jonathan@openworklabs.com), but no email confirmation came (tried multiple emails)
- Tried Hub Init, but the command just hangs, no matter what username I try

A side note:

`hub keys ls` also hangs

**Comment by carsonfarmer** [comment]
I think this was a Hub update glitch, but should be resolved now. Please re-open if this is not the case.
