### ISSUE TITLE
Bucket push: Parsing event in validate write: SyntaxError: invalid character '.' in string

### ISSUE THREAD

**Issue by andrewxhill** [textileio/textile#459]
Unknown issue with pushing a bucket from Windows CLI.

`Parsing event in validate write: SyntaxError: invalid character '.' in string`

**Comment by carsonfarmer** [comment]
Just to update, this appears to be an issue with windows `\` and the parsing logic of the cli lib we're using. We'll have to normalize the paths or find a lib that handles cross-platform file paths properly.

**Comment by sanderpick** [comment]
We should be using `path/filepath` everywhere in the CLI, which is designed for that purpose (cross platform), as opposed to `path` which always uses forward slashes for URLs and Linux systems. 

Do we have a way to reproduce this issue?

**Comment by sanderpick** [comment]
Fixed in https://github.com/textileio/textile/pull/467. We can do a release, but trying to tag one more thing in first.
