### ISSUE TITLE
Hub sends wront Content-Type header for SVG

### ISSUE THREAD

**Issue by tennox** [textileio/textile#556]
When requesting an SVG file via textile.space link, the server responds with:
`content-type:	text/xml; charset=utf-8`
but images won't display, it needs e.g.:
`image/svg+xml`

### Example:
https://bafzbeiafonhiqdag65i7qlbrbvrn344sigidimbcyypcm5owpqagatcce4.textile.space/static/media/eth-symbol-virgil.15eeeeeb.svg

works fine on e.g. **dweb.link**:
https://bafzbeiafonhiqdag65i7qlbrbvrn344sigidimbcyypcm5owpqagatcce4.dweb.link/static/media/eth-symbol-virgil.15eeeeeb.svg

### Codepen
https://codepen.io/tennox/pen/LYWbrgM

**Comment by andrewxhill** [comment]
pretty sure this was fixed here: https://github.com/textileio/textile/pull/555

```
content-type: image/svg+xml
date: Wed, 16 Jun 2021 11:23:44 GMT
```

**Comment by tennox** [comment]
Yes, great, I was checking cached results :see_no_evil: 

:+1:
