### ISSUE TITLE
Refactor core components

### ISSUE THREAD

**Issue by andrewxhill** [textileio/textile#65]
I was about to fix this notice about scope switching real quick (https://github.com/textileio/textile/issues/42) but wondered if we could clean up the layers at the beginning.

Summary of current flow is:

- user login
- creates a new 'user' namespace locally linked to their email
- user can then create teams
- user can switch between teams by `textile teams switch ...`
- user can switch back to personal account by `textile switch...`

A simplification here that could solve some issues I had when I first started playing with the current layouit,

- user login
- creates a new 'user' but immediately creates a team for that user. that could be 'personal' or drawn from a random list of words, it doesn't matter so much
- user than can create new teams
- only one switch, `textile teams switch ...` nothing really operates for now at the root user layer (until we have some features that require it at least)

Some things this solves

- only onboard people with one concept to switch around on, a team
- when i onboarded and started creating projects, really quickly i wanted to invite people to those projects, but realizing that i have to go back and create a team first, then projects (first removing old project), then invite.
- if every project has a team by default we can do another enhancement

additional enhancement:

- when a user cc's into a folder where a Project is already initialized, it could immediately switch the user to working within that team. team id could just be added to the yaml to make this quick enough. perhaps there are ways to provide queues in the terminal about the team/project name at all times, e.g. `~/Textile/textile(andrew/minor-fixes)$` my git setup always showing me the current branch in git.

**Comment by sanderpick** [comment]
> Some things this solves 
>     * only onboard people with one concept to switch around on, a team

We could just get rid of the `team switch` command (the root one covers it anyway) if this is confusing. 

>     * when i onboarded and started creating projects, really quickly i wanted to invite people to those projects, but realizing that i have to go back and create a team first, then projects (first removing old project), then invite.

This would require a pretty big refactor. If adding people to projects like this is a needed feature, I'd propose just severing the notion that a project is owned by a team or person... then you could add people or teams to projects. Again, a good amount of work, but sounds like a reasonable change. 

>     * when a user cc's into a folder where a Project is already initialized, it could immediately switch the user to working within that team. team id could just be added to the yaml to make this quick enough. perhaps there are ways to provide queues in the terminal about the team/project name at all times, e.g. `~/Textile/textile(andrew/minor-fixes)$` my git setup always showing me the current branch in git.

The current scope is held on the session, as in, on the server. So, `cd` alone won't be able to alter the session.

**Comment by andrewxhill** [comment]
well... this is the smallest refactor it's ever going to be that's why i'm flagging it now so we can walk through the options.

> We could just get rid of the team switch command (the root one covers it anyway) if this is confusing.

that makes sense to me. 

> This would require a pretty big refactor. If adding people to projects like this is a needed feature, I'd propose just severing the notion that a project is owned by a team or person... then you could add people or teams to projects. Again, a good amount of work, but sounds like a reasonable change.

Going to do the other two parts out of order, because I'm confused or missing an idea,

> The current scope is held on the session, as in, on the server. So, cd alone won't be able to alter the session.

I figured that the scope stored in the .textile/config.yml would be enough to kick off a new session automatically. as in

1. i'm in folder+project, `/ram` with a session.
2. i cd into another exiting folder+project, `/mugs`

at which point i assumed it would have enough to change the session based on my user id and that scope in `/mugs/.textile/config.yml`. or are you thinking the user will have to re-login when they do that change directory step?

if it is possible, i figured we could just include which team it should be in that same yml file to help those switches happen smoothly.

okay, last part,

> This would require a pretty big refactor. If adding people to projects like this is a needed feature, I'd propose just severing the notion that a project is owned by a team or person... then you could add people or teams to projects. Again, a good amount of work, but sounds like a reasonable change.

all i'm saying is, when a user uses the CLI the first time have it create a default team for them and switch them into the team right away so they don't create new projects under their naked account.

i like your proposal of de-linking them better, if not huge work. i think that is probably the most natural. i just create projects and then assign them to the team/account i want them managed under once i know what i'm doing and try to push them to the world... nice

**Comment by sanderpick** [comment]
Cool, sounds good! This change will make the point about scope being defined local or remote mute, but just to clarify, it used to be defined how you assumed above, but it's now embedded in the session. There's a lengthy description of the change on a PR somewhere, but the gist is that I found it to be quite confusing. Scope changes out from under your feet based on directory. The compromise was to still include scope in the config, meaning that you can still _lock_ a scope per directory if you want. In any case, this won't matter at all if projects contain teams / users, vs. the other way around.
