### ISSUE TITLE
Render buckets over a dedicated domain

### ISSUE THREAD

**Issue by sanderpick** [textileio/textile#87]
Mentioned by @andrewxhill, due to security concerns, bucket rendering should happen under a dedicated domain. For example, github pages are rendered under github.io.

**Comment by andrewxhill** [comment]
i don't know much about it, i just remembered when they migrated from `.com` that being the case. here's the quote from the blog post and link,

_Beginning today, all GitHub Pages sites are moving to a new, dedicated
domain: github.io. This is a security measure aimed at removing potential
vectors for cross domain attacks targeting the main github.com session as well
as vectors for phishing attacks relying on the presence of the “github.com”
domain to build a false sense of trust in malicious websites._

https://github.blog/2013-04-05-new-github-pages-domain-github-io/
