### ISSUE TITLE
cli: projects init help lists path as a flag but it needs to be just the first arg

### ISSUE THREAD

**Issue by andrewxhill** [textileio/textile#96]
```
Usage:
  textile projects init [flags]

Flags:
  -h, --help          help for init
      --path string   Project path (default ".")
```

**Comment by sanderpick** [comment]
The first arg is the project "name". The path flag can be used to point at a different local path. By default, this is just the current working directory.

**Comment by andrewxhill** [comment]
fixed in https://github.com/textileio/textile/pull/97
